### ISSUE TITLE
Schema inference broken under Python 2

### ISSUE THREAD

**Issue by pudo** [okfn/jsontableschema-py#19]
The following happens when running ``jtskit infer`` under Python 2:

```bash
(wrangle)> $ ~/.virtualenvs/wrangle/bin/jtskit infer tests/fixtures/everypol/term-26.csv                                                        [±master ●]
/Users/fl/.virtualenvs/wrangle/lib/python2.7/site-packages/jtskit/cli.py:16: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.group()
/Users/fl/.virtualenvs/wrangle/lib/python2.7/site-packages/jtskit/cli.py:24: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.option('--to_file')
/Users/fl/.virtualenvs/wrangle/lib/python2.7/site-packages/jtskit/cli.py:53: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.argument('schema')
Traceback (most recent call last):
  File "/Users/fl/.virtualenvs/wrangle/bin/jtskit", line 11, in <module>
    sys.exit(main())
  File "/Users/fl/.virtualenvs/wrangle/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/fl/.virtualenvs/wrangle/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/fl/.virtualenvs/wrangle/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/fl/.virtualenvs/wrangle/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fl/.virtualenvs/wrangle/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/fl/.virtualenvs/wrangle/lib/python2.7/site-packages/jtskit/cli.py", line 43, in infer
    response = jtskit.infer(headers, values, row_limit=row_limit)
  File "/Users/fl/.virtualenvs/wrangle/lib/python2.7/site-packages/jtskit/infer.py", line 53, in infer
    for index, row in enumerate(values):
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 43: ordinal not in range(128)
```

**Comment by pwalsh** [comment]
@pudo ok will check when I get back tomorrow. Tests pass on Py2, and I'm pretty sure that @trickvi used it for OS stuff too.

**Comment by pwalsh** [comment]
@pudo sorry for the long delay here.

We'll be looking at this shortly.

**Comment by pwalsh** [comment]
fixed in coming release
